### ISSUE TITLE
Installation failed when doing migration

### ISSUE THREAD

**Issue by KinGsNowGH** [gtt-project/redmine_text_blocks#10]
**Problem**
Migration failed when trying to install on container.

**To Reproduce**
Docker Container sameersbn/redmine 3.4.13 clean install.

**Screenshots**
```
2021-02-24T19:34:16.065495547Z rake aborted!
2021-02-24T19:34:16.065630400Z NoMethodError: undefined method `[]' for #<ActiveRecord::Migration:0x00000000021b6ed8>
2021-02-24T19:34:16.066191211Z /home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.11.1/lib/active_record/migration.rb:664:in `block in method_missing'
2021-02-24T19:34:16.066221827Z /home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.11.1/lib/active_record/migration.rb:634:in `block in say_with_time'
2021-02-24T19:34:16.066233657Z /home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.11.1/lib/active_record/migration.rb:634:in `say_with_time'
2021-02-24T19:34:16.066240785Z /home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.11.1/lib/active_record/migration.rb:654:in `method_missing'
2021-02-24T19:34:16.066249019Z /home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.11.1/lib/active_record/migration.rb:416:in `method_missing'
2021-02-24T19:34:16.066255598Z /home/redmine/redmine/plugins/redmine_text_blocks/db/migrate/20170831050051_create_text_blocks.rb:1:in `<top (required)>'
2021-02-24T19:34:16.066280922Z /home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
2021-02-24T19:34:16.066288315Z /home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
2021-02-24T19:34:16.066294974Z /home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:274:in `block in require'
2021-02-24T19:34:16.066301661Z /home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:240:in `load_dependency'
2021-02-24T19:34:16.066308236Z /home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:274:in `require'
2021-02-24T19:34:16.066314687Z /home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.11.1/lib/active_record/migration.rb:777:in `load_migration'
2021-02-24T19:34:16.066321021Z /home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.11.1/lib/active_record/migration.rb:773:in `migration'
2021-02-24T19:34:16.066327345Z /home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.11.1/lib/active_record/migration.rb:768:in `disable_ddl_transaction'
2021-02-24T19:34:16.066333790Z /home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.11.1/lib/active_record/migration.rb:1076:in `use_transaction?'
2021-02-24T19:34:16.066340270Z /home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.11.1/lib/active_record/migration.rb:986:in `rescue in block in migrate'
2021-02-24T19:34:16.066347720Z /home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.11.1/lib/active_record/migration.rb:983:in `block in migrate'
2021-02-24T19:34:16.066354444Z /home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.11.1/lib/active_record/migration.rb:980:in `each'
2021-02-24T19:34:16.066360884Z /home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.11.1/lib/active_record/migration.rb:980:in `migrate'
2021-02-24T19:34:16.066367193Z /home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.11.1/lib/active_record/migration.rb:823:in `up'
2021-02-24T19:34:16.066373464Z /home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.11.1/lib/active_record/migration.rb:801:in `migrate'
2021-02-24T19:34:16.066379947Z /home/redmine/redmine/lib/redmine/plugin.rb:481:in `migrate_plugin'
2021-02-24T19:34:16.066386142Z /home/redmine/redmine/lib/redmine/plugin.rb:453:in `migrate'
2021-02-24T19:34:16.066392252Z /home/redmine/redmine/lib/redmine/plugin.rb:467:in `block in migrate'
2021-02-24T19:34:16.066398282Z /home/redmine/redmine/lib/redmine/plugin.rb:466:in `each'
2021-02-24T19:34:16.066404267Z /home/redmine/redmine/lib/redmine/plugin.rb:466:in `migrate'
2021-02-24T19:34:16.066410440Z /home/redmine/redmine/lib/tasks/redmine.rake:135:in `block (3 levels) in <top (required)>'
2021-02-24T19:34:16.066416808Z /home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/rake-13.0.1/exe/rake:27:in `<top (required)>'
2021-02-24T19:34:16.066752141Z
2021-02-24T19:34:16.066769034Z Caused by:
2021-02-24T19:34:16.067158071Z NoMethodError: undefined method `[]' for #<ActiveRecord::Migration:0x00000000021b6ed8>
2021-02-24T19:34:16.067562477Z /home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.11.1/lib/active_record/migration.rb:664:in `block in method_missing'
2021-02-24T19:34:16.067582292Z /home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.11.1/lib/active_record/migration.rb:634:in `block in say_with_time'
2021-02-24T19:34:16.067590895Z /home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.11.1/lib/active_record/migration.rb:634:in `say_with_time'
2021-02-24T19:34:16.067597922Z /home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.11.1/lib/active_record/migration.rb:654:in `method_missing'
2021-02-24T19:34:16.067604870Z /home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.11.1/lib/active_record/migration.rb:416:in `method_missing'
2021-02-24T19:34:16.067611817Z /home/redmine/redmine/plugins/redmine_text_blocks/db/migrate/20170831050051_create_text_blocks.rb:1:in `<top (required)>'
2021-02-24T19:34:16.067618831Z /home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
2021-02-24T19:34:16.067625576Z /home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
2021-02-24T19:34:16.067632189Z /home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:274:in `block in require'
2021-02-24T19:34:16.067639025Z /home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:240:in `load_dependency'
2021-02-24T19:34:16.067645587Z /home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:274:in `require'
2021-02-24T19:34:16.067652166Z /home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.11.1/lib/active_record/migration.rb:777:in `load_migration'
2021-02-24T19:34:16.067658714Z /home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.11.1/lib/active_record/migration.rb:773:in `migration'
2021-02-24T19:34:16.067665404Z /home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.11.1/lib/active_record/migration.rb:768:in `disable_ddl_transaction'
2021-02-24T19:34:16.067671992Z /home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.11.1/lib/active_record/migration.rb:1076:in `use_transaction?'
2021-02-24T19:34:16.067678621Z /home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.11.1/lib/active_record/migration.rb:1068:in `ddl_transaction'
2021-02-24T19:34:16.067685909Z /home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.11.1/lib/active_record/migration.rb:1022:in `execute_migration_in_transaction'
2021-02-24T19:34:16.067692936Z /home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.11.1/lib/active_record/migration.rb:984:in `block in migrate'
2021-02-24T19:34:16.067699739Z /home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.11.1/lib/active_record/migration.rb:980:in `each'
2021-02-24T19:34:16.067716291Z /home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.11.1/lib/active_record/migration.rb:980:in `migrate'
2021-02-24T19:34:16.067724173Z /home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.11.1/lib/active_record/migration.rb:823:in `up'
2021-02-24T19:34:16.067731170Z /home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.11.1/lib/active_record/migration.rb:801:in `migrate'
2021-02-24T19:34:16.067737756Z /home/redmine/redmine/lib/redmine/plugin.rb:481:in `migrate_plugin'
2021-02-24T19:34:16.067743970Z /home/redmine/redmine/lib/redmine/plugin.rb:453:in `migrate'
2021-02-24T19:34:16.067750160Z /home/redmine/redmine/lib/redmine/plugin.rb:467:in `block in migrate'
2021-02-24T19:34:16.067756409Z /home/redmine/redmine/lib/redmine/plugin.rb:466:in `each'
2021-02-24T19:34:16.067762533Z /home/redmine/redmine/lib/redmine/plugin.rb:466:in `migrate'
2021-02-24T19:34:16.067768661Z /home/redmine/redmine/lib/tasks/redmine.rake:135:in `block (3 levels) in <top (required)>'
2021-02-24T19:34:16.067775222Z /home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/rake-13.0.1/exe/rake:27:in `<top (required)>'
2021-02-24T19:34:16.068107769Z Tasks: TOP => redmine:plugins:migrate
2021-02-24T19:34:16.068125200Z (See full trace by running task with --trace)
2021-02-24T19:34:16.147696497Z Migrating bestest_markdown_editor (Bestest Markdown Editor)...
2021-02-24T19:34:16.147750227Z Migrating bestest_sidebar_annihilator (Bestest Side-Bar Annihilator for Redmine)...
2021-02-24T19:34:16.147760669Z Migrating clipboard_image_paste (Clipboard image paste)...
2021-02-24T19:34:16.147768178Z Migrating customfield_checkbox_utility (Customfield Checkbox Utility plugin)...
2021-02-24T19:34:16.147774919Z Migrating periodictask (Redmine Periodictask plugin)...
2021-02-24T19:34:16.147781217Z Migrating plus_gantt (Gantt Plus plugin)...
2021-02-24T19:34:16.147787433Z Migrating progressive_projects_list (Progressive Projects List plugin)...
2021-02-24T19:34:16.147793617Z Migrating redmine_all_thumbnails (Redmine All Thumbnails)...
2021-02-24T19:34:16.147799852Z Migrating redmine_base_deface (Redmine Base Deface plugin)...
2021-02-24T19:34:16.147806055Z Migrating redmine_checklists (Redmine Checklists plugin (Light version))...
2021-02-24T19:34:16.147812350Z Migrating redmine_ckeditor (Redmine CKEditor plugin)...
2021-02-24T19:34:16.147818577Z Migrating redmine_custom_reports (Redmine Custom Reports (with charts) plugin)...
2021-02-24T19:34:16.147824791Z Migrating redmine_dashboard (Redmine Dashboard plugin)...
2021-02-24T19:34:16.147830833Z Migrating redmine_default_custom_query (Redmine Default Custom Query)...
2021-02-24T19:34:16.147838767Z Migrating redmine_didyoumean (Did You Mean?)...
2021-02-24T19:34:16.147844879Z Migrating redmine_dmsf (DMSF)...
2021-02-24T19:34:16.147850873Z Migrating redmine_impersonate (Redmine Impersonate)...
2021-02-24T19:34:16.147856940Z Migrating redmine_issue_attachments (Issue Attachments)...
2021-02-24T19:34:16.147884269Z Migrating redmine_issue_dynamic_edit (Redmine Dynamic edit Issue plugin)...
2021-02-24T19:34:16.147891611Z Migrating redmine_issue_evm (Redmine Issue Evm plugin)...
2021-02-24T19:34:16.147897798Z Migrating redmine_issue_history_tabs (Redmine Issue History Tabs plugin)...
2021-02-24T19:34:16.147904066Z Migrating redmine_issue_todo_lists (Issue To-do Lists Plugin)...
2021-02-24T19:34:16.147910180Z Migrating redmine_issue_view_columns (Redmine Issue View Columns)...
2021-02-24T19:34:16.147916344Z Migrating redmine_issues_tree (Redmine Issues Tree plugin)...
2021-02-24T19:34:16.147922567Z Migrating redmine_logs (Redmine Logs plugin)...
2021-02-24T19:34:16.147928591Z Migrating redmine_mermaid_macro (Redmine Mermaid Macro plugin)...
2021-02-24T19:34:16.147934732Z Migrating redmine_more_context (Redmine More Context)...
2021-02-24T19:34:16.147940880Z Migrating redmine_more_filters (Redmine More Filters)...
2021-02-24T19:34:16.147946997Z Migrating redmine_my_roadmaps (My Roadmaps plugin)...
2021-02-24T19:34:16.147953153Z Migrating redmine_per_project_formatting (Redmine per project formatting plugin)...
2021-02-24T19:34:16.147959323Z Migrating redmine_percent_done (Redmine Issue Done Ratio Plugin)...
2021-02-24T19:34:16.147965499Z Migrating redmine_recurring_tasks (Redmine Recurring Tasks)...
2021-02-24T19:34:16.147974080Z Migrating redmine_searchable_selectbox (Redmine Searchable Selectbox)...
2021-02-24T19:34:16.147982526Z Migrating redmine_silencer (Redmine Silencer 2)...
2021-02-24T19:34:16.147988931Z Migrating redmine_tags (Redmine Tags)...
2021-02-24T19:34:16.147995095Z Migrating redmine_text_blocks (Redmine Text Blocks Plugin)...
2021-02-24T19:34:16.148001352Z -- [](5.2)
2021-02-24T19:34:16.148007568Z -- [](5.2)
```

**Platform/smartphone:**
```
Environment:
  Redmine version                3.4.13.stable
  Ruby version                   2.3.8-p459 (2018-10-18) [x86_64-linux-gnu]
  Rails version                  4.2.11.1
  Environment                    production
  Database adapter               Mysql2
  Database timezone              -03
  ActiveRecord timezone          local
  App timezone                   UTC
```

**Comment by sanak** [comment]
@KinGsNowGH
Thanks for your feedback!

I noticed that Redmine required version is still old in `README.md` and `init.rb`,
- https://github.com/gtt-project/redmine_text_blocks/blob/main/README.md#requirements
- https://github.com/gtt-project/redmine_text_blocks/blob/main/init.rb#L15

although, we changed Redmine minimum required version from 3.4 to 4.0.
- https://github.com/gtt-project/redmine_text_blocks/commit/6a15bd77954459cc0450080eeae0e74048e88f4c

We will fix `README.md` and `init.rb` side Redmine minimum required version (from 3.4 to 4.0) soon,
So, if using Redmine 4.0 is no problem for you, then could you try Redmine 4.0 version ?

Thanks,
